### ISSUE TITLE
Exercise 4 : Events

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JQ-Track#2]
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/inputHint.js
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/tabs.js

You should understand what events are, how to bind and unbind them with elements. Understand what an event object contains and how it can be useful. How do you initiate an event programmatically using $.fn.trigger.

4.1 Create an input hint
Open the file /exercises/index.html in your browser. Use the file /exercises/js/inputHint.js or work in Firebug. Your task is to use the text of the label for the search input to create “hint” text for the search input. The steps are as follows:
Set the value of the search input to the text of the label element
Add a class of “hint” to the search input
Remove the label element
Bind a focus event to the search input that removes the hint text and the “hint” class
Bind a blur event to the search input that restores the hint text and “hint” class if no search text was entered

4.2 Add tabbed navigation
Open the file /exercises/index.html in your browser. Use the file /exercises/js/tabs.js. Your task is to create tabbed navigation for the two div.module elements. To accomplish this:
Hide all of the modules.
Create an unordered list element before the first module.
Iterate over the modules using $.fn.each. For each module, use the text of the h2 element as the text for a list item that you add to the unordered list element.
Bind a click event to the list item that:
Shows the related module, and hides any other modules.
Adds a class of “current” to the clicked list item.
Removes the class “current” from the other list item.
Finally, show the first tab.

**Comment by segunadeleye** [comment]
- Use 2-space indentation
- Please add a link to the javascript file.

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
- Use the correct convention for jQuery object variables.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/inputHint.js#L8
  Do you need `.eq(0)` for the label and the input?
- https://github.com/segunadeleye/jqfundamentals/blob/master/exercises/Ex4/inputHint.js#L11 and https://github.com/segunadeleye/jqfundamentals/blob/master/exercises/Ex4/inputHint.js#L13
  Use chaining.

**Comment by damilola-dealdey** [comment]
Redone

**Comment by segunadeleye** [comment]
Looks good
