### ISSUE TITLE
Exercise 6

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JQ-Track#4]
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/load.js
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/specials.js

Ajax
You should know how to make Ajax request using jQuery. How to handle responses, error and failures during an Ajax request.

6.1 Load External Content
Open the file /exercises/index.html in your browser. Use the file /exercises/js/load.js. Your task is to load the content of a blog item when a user clicks on the title of the item.
Create a target div after the headline for each blog post and store a reference to it on the headline element using $.fn.data.
Bind a click event to the headline that will use the $.fn.load method to load the appropriate content from /exercises/data/blog.html into the target div. Don't forget to prevent the default action of the click event.

6.2 Load content using JSON
Open the file /exercises/index.html in your browser. Use the file /exercises/js/specials.js. Your task is to show the user details about the special for a given day when the user selects a day from the select dropdown.
Append a target div after the form that's inside the #specials element; this will be where you put information about the special once you receive it. Bind to the change event of the select element; when the user changes the selection, send an Ajax request to /exercises/data/specials.json.
When the request returns a response, use the value the user selected in the select (hint: $.fn.val) to look up information about the special in the JSON response.
Add some HTML about the special to the target div you created.
Finally, because the form is now Ajax-enabled, remove the submit button from the form.

**Comment by segunadeleye** [comment]
- Use the correct convention for jQuery object variables.

### load.js
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/load.js#L12
  You don't have to add the click event within the loop.
- The click event should be on the headline and not on the list. Also, the target `div` should be inserted after the headline, not after the list.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/load.js#L15
  Don't use `:first` here.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/load.js#L15-L16
  Why did you do a double assignment here?

### specials.js
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/specials.js#L6-L7
  These don't have to be object variables.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/specials.js#L14
  A clearer variable name would be `selectedDay`.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/specials.js#L23-L24
  Note that `append` takes more than one argument. The elements are appended in the order in which they are passed as arguments.

**Comment by damilola-dealdey** [comment]
Changes Made

**Comment by segunadeleye** [comment]
Good
